### Consider following code to answer further questions:

In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_)

### Q1. Is there any difference in the data type of variables `list_` and `array_list`? If there is, then write a code to print the data types of both the variables.

A1. Basically, the `list_` is a Python list, and its data type is `<class 'list'>`.
While `array_list` is a NumPy array, and its data type is `<class 'numpy.ndarray'>`. Both has different niche & different collections of functions to work with. 

In [3]:
import numpy as np

print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))

Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


### Q2. Write a code to print the data type of each and every element of both the variables `list_` and `array_list`.


In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>



### Q3. Considering the following changes in the variable, `array_list = np.array(object = list_, dtype = int)`. Will there be any difference in the data type of the elements present in both the variables `list_` and `array_list`? If so, print the data types of each and every element present in both the variables `list_` and `array_list`.

A3. After specifying `dtype=int` in `np.array()`, `array_list` will have integer elements.
While `list_` remains unchanged with its elements as strings (`<class 'str'>`).

In [5]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data types of elements in list_:")
for item in list_:
    print(type(item))

# Print data type of each element in array_list
print("\nData types of elements in array_list:")
for item in array_list:
    print(type(item))

Data types of elements in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data types of elements in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### Consider the below code to answer further questions:


In [6]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

### Q4. Write a code to find the following characteristics of variable, `num_array`:
(i) **Shape**
(ii) **Size**


In [7]:

#A4.

# (i) Print the shape of num_array
print("Shape of num_array:", num_array.shape)

# (ii) Print the size of num_array
print("Size of num_array:", num_array.size)

Shape of num_array: (2, 3)
Size of num_array: 6



### Q5. Write a code to create a NumPy array of a 3x3 matrix containing zeros only, using a NumPy array creation function.


In [8]:
#A5.
import numpy as np

# Create a 3x3 matrix of zeros
zero_matrix = np.zeros((3, 3))

print("3x3 matrix of zeros:")
print(zero_matrix)

3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



### Q6. Create an identity matrix of shape (5,5) using NumPy functions.


In [9]:
#A6.
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

print("5x5 identity matrix:")
print(identity_matrix)

5x5 identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
